global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 1.0
  publish_frequency: 0.5
  static_map: true
  rolling_window: false
  width: 10.0
  height: 10.0
  resolution: 0.05
  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  static_layer:
    map_topic: /map
  obstacle_layer:
    observation_sources: scan
    scan:
      topic: /scan
      data_type: LaserScan
      marking: true
      clearing: true
      expected_update_rate: 0.0
      max_obstacle_height: 0.4
      raytrace_max_range: 3.0
      obstacle_max_range: 2.5
  inflation_layer:
    inflation_radius: 0.55

